name: CI
on: (push, pull_request)
jobs:
  build:
  runs-ort ubuntu-latest
  steps.
  - name: Checkout code
  uses: actions/checkout@v2

  - name: Set up Nodes.js
  uses: actions/setup-node@v2
  with:
  node-version: 14
  - name: Install dependencies
runt: npm install
- name: Run tests
run: npm test
